name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        registry: ${{ secrets.ACR_LOGIN_SERVER }}

    - name: Build and push Angular image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/spicecraft-client:latest ./spicecraft.client
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/spicecraft-client:latest

    - name: Build and push .NET Core image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/spicecraft-server:latest ./SpiceCraft.Server
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/spicecraft-server:latest

    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instances
      run: |
        az container create --resource-group rg-spice-craft --name spicecraft-client --image ${{ secrets.ACR_LOGIN_SERVER }}/spicecraft-client:latest --cpu 1 --memory 1 --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }} --dns-name-label spicecraft-client --ports 80
        az container create --resource-group rg-spice-craft --name spicecraft-server --image ${{ secrets.ACR_LOGIN_SERVER }}/spicecraft-server:latest --cpu 1 --memory 1 --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} --registry-username ${{ secrets.ACR_USERNAME }} --registry-password ${{ secrets.ACR_PASSWORD }} --dns-name-label spicecraft-server --ports 80
