version: '3.4'

services:
  spicecraft-client:
    build:
      context: ./spicecraft.client
      dockerfile: Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/spicecraft-client:latest
    ports:
      - "80:80"

  spicecraft-server:
    build:
      context: .
      dockerfile: SpiceCraft.Server/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/spicecraft-server:latest
    ports:
      - "8080:8080"     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080      
      - ConnectionStrings__DefaultConnection=Server=ASPNETCORE_URLS="https://+;http://+"spicecraft-mssql;Database=SpiceCraftDb;User=sa;Password=${MSSQL_SA_PASSWORD}
    depends_on:
      - spicecraft-mssql

  spicecraft-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
