version: '3.4'

services:
  spicecraft-client:
    image: ${DOCKER_REGISTRY-}spicecraft-client
    build:
      context: .
      dockerfile: spicecraft.client/Dockerfile

  spicecraft-server:
    image: ${DOCKER_REGISTRY-}spicecraft-server
    build:
      context: .
      dockerfile: SpiceCraft.Server/Dockerfile
