version: '3.4'

services:
  spicecraft-client:
    build:
      context: .
      dockerfile: spicecraft.client/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/spicecraft-client:latest
    ports:
      - "8082:80"
    

  spicecraft-server:
    build:
      context: .
      dockerfile: SpiceCraft.Server/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/spicecraft-server:latest
    ports:
      - "8080:80"

    
