version: '3.4'

services:
  spicecraft-client:
    build:
      context: .
      dockerfile: spicecraft.client/Dockerfile
    ports:
      - "8082:80"
    

  spicecraft-server:
    build:
      context: .
      dockerfile: SpiceCraft.Server/Dockerfile
    ports:
      - "8080:80"

    
