version: '3.4'

services:
  spicecraft-client:
    build:
      context: spicecraft.client/
      dockerfile: spicecraft.client/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/spicecraft-client:latest
    ports:
      - "80:80"
    

  spicecraft-server:
    build:
      context: SpiceCraft.Server/
      dockerfile: SpiceCraft.Server/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/spicecraft-server:latest
    ports:
      - "8080:8080"

    
