using SpiceCraft.Server.ML.Models.SentitmentAnalysis;

namespace SpiceCraft.Server.ML.RatingSentiment;

public class SentitmentTrainingData
{

public static List<RatingDescriptionData> GetTrainingData()
    {
        return new List<RatingDescriptionData>
        {
            new RatingDescriptionData { RatingDescription = "This is the best meal I've ever had!", Label = true },
            new RatingDescriptionData { RatingDescription = "The product quality is amazing.", Label = true },
            new RatingDescriptionData { RatingDescription = "I would definitely recommend this to others.", Label = true },
            new RatingDescriptionData { RatingDescription = "The service was excellent and the food was great!", Label = true },
            new RatingDescriptionData { RatingDescription = "I am very satisfied with my purchase.", Label = true },
            new RatingDescriptionData { RatingDescription = "Totally worth the price.", Label = true },
            new RatingDescriptionData { RatingDescription = "Delicious food, great service.", Label = true },
            new RatingDescriptionData { RatingDescription = "Everything was perfect, loved it!", Label = true },
            new RatingDescriptionData { RatingDescription = "The item exceeded my expectations.", Label = true },
            new RatingDescriptionData { RatingDescription = "Quick delivery and tasty food.", Label = true },
            new RatingDescriptionData { RatingDescription = "Absolutely fantastic! Will order again.", Label = true },
            new RatingDescriptionData { RatingDescription = "The portions were generous and well-cooked.", Label = true },
            new RatingDescriptionData { RatingDescription = "I had a wonderful experience.", Label = true },
            new RatingDescriptionData { RatingDescription = "I am happy with the quality of the product.", Label = true },
            new RatingDescriptionData { RatingDescription = "The taste was just right, I really enjoyed it.", Label = true },
            new RatingDescriptionData { RatingDescription = "I was pleasantly surprised by the freshness.", Label = true },
            new RatingDescriptionData { RatingDescription = "Good value for money.", Label = true },
            new RatingDescriptionData { RatingDescription = "Everything was just great.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was absolutely delightful!", Label = true },
            new RatingDescriptionData { RatingDescription = "Great service, tasty food.", Label = true },

            new RatingDescriptionData { RatingDescription = "Meh, it was okay but nothing special.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was average.", Label = false },
            new RatingDescriptionData { RatingDescription = "Not the best, but not the worst.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was decent, but could be better.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was alright, but I've had better.", Label = false },
            new RatingDescriptionData { RatingDescription = "Nothing too special about it.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was fine, nothing too exciting.", Label = false },
            new RatingDescriptionData { RatingDescription = "I expected a little more.", Label = false },
            new RatingDescriptionData { RatingDescription = "The product is just okay.", Label = false },
            new RatingDescriptionData { RatingDescription = "Not bad, but not great either.", Label = false },
            new RatingDescriptionData { RatingDescription = "Decent meal for the price.", Label = false },
            new RatingDescriptionData { RatingDescription = "The delivery was on time, but the food was just okay.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was passable, not remarkable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The experience was pretty standard.", Label = false },
            new RatingDescriptionData { RatingDescription = "An average meal, nothing to write home about.", Label = false },
            new RatingDescriptionData { RatingDescription = "The quality was acceptable.", Label = false },
            new RatingDescriptionData { RatingDescription = "Okay service, nothing stood out.", Label = false },
            new RatingDescriptionData { RatingDescription = "It met my expectations, but didn’t exceed them.", Label = false },
            new RatingDescriptionData { RatingDescription = "Reasonable quality, but nothing special.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a decent experience overall.", Label = false },

            new RatingDescriptionData { RatingDescription = "This was the worst experience I've ever had.", Label = false },
            new RatingDescriptionData { RatingDescription = "I was very disappointed with the product.", Label = false },
            new RatingDescriptionData { RatingDescription = "Terrible service, the staff was rude.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food arrived cold and tasted horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "This is the last time I'll be ordering from here.", Label = false },
            new RatingDescriptionData { RatingDescription = "I wouldn’t recommend this to anyone.", Label = false },
            new RatingDescriptionData { RatingDescription = "The item was damaged and of poor quality.", Label = false },
            new RatingDescriptionData { RatingDescription = "The delivery was extremely late.", Label = false },
            new RatingDescriptionData { RatingDescription = "I hated the taste, it was disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "Absolutely horrible, a waste of money.", Label = false },
            new RatingDescriptionData { RatingDescription = "The product broke after one use.", Label = false },
            new RatingDescriptionData { RatingDescription = "Customer service was awful.", Label = false },
            new RatingDescriptionData { RatingDescription = "Very poor quality and extremely overpriced.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was a complete disaster.", Label = false },
            new RatingDescriptionData { RatingDescription = "Overcooked and tasteless food.", Label = false },
            new RatingDescriptionData { RatingDescription = "I was shocked by how bad the service was.", Label = false },
            new RatingDescriptionData { RatingDescription = "It took forever to get my order and it was wrong.", Label = false },
            new RatingDescriptionData { RatingDescription = "The staff was extremely rude.", Label = false },
            new RatingDescriptionData { RatingDescription = "Extremely disappointed with the quality.", Label = false },
            new RatingDescriptionData { RatingDescription = "I will never order from here again.", Label = false },
            new RatingDescriptionData { RatingDescription = "Total waste of money.", Label = false },
            new RatingDescriptionData { RatingDescription = "Not worth the price at all.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was undercooked and inedible.", Label = false },
            new RatingDescriptionData { RatingDescription = "The worst customer experience ever.", Label = false },
            new RatingDescriptionData { RatingDescription = "Everything was just awful.", Label = false },
            new RatingDescriptionData { RatingDescription = "Horrible, wouldn’t recommend.", Label = false },
            new RatingDescriptionData { RatingDescription = "The worst decision to buy this.", Label = false },
            new RatingDescriptionData { RatingDescription = "Completely unsatisfied with my purchase.", Label = false },
            new RatingDescriptionData { RatingDescription = "Absolutely not worth it, very bad experience.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was burnt and tasted terrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "Extremely rude and unhelpful staff.", Label = false },
            new RatingDescriptionData { RatingDescription = "The item arrived broken and late.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food tasted old and stale.", Label = false },
            new RatingDescriptionData { RatingDescription = "The restaurant was filthy, and the food was gross.", Label = false },
            new RatingDescriptionData { RatingDescription = "The experience was a nightmare.", Label = false },
            new RatingDescriptionData { RatingDescription = "I will never come back here.", Label = false },
            new RatingDescriptionData { RatingDescription = "Overpriced for what you get.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food had no flavor and was cold.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a terrible mistake to order from here.", Label = false },
            new RatingDescriptionData { RatingDescription = "Very bad quality, not worth it.", Label = false },
             new RatingDescriptionData { RatingDescription = "The service was horrible and the staff was extremely rude.", Label = false },
            new RatingDescriptionData { RatingDescription = "Absolutely disgusting! I wouldn't feed this to my worst enemy.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food tasted like garbage and was a complete waste of money.", Label = false },
            new RatingDescriptionData { RatingDescription = "This was by far the worst dining experience of my life.", Label = false },
            new RatingDescriptionData { RatingDescription = "Terrible food, awful service, and ridiculous prices.", Label = false },
            new RatingDescriptionData { RatingDescription = "I regret every penny spent on this disaster of a meal.", Label = false },
            new RatingDescriptionData { RatingDescription = "The chicken was undercooked and raw, absolutely disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "They should be ashamed to serve such horrible food.", Label = false },
            new RatingDescriptionData { RatingDescription = "The waitstaff had a horrible attitude and completely ruined my meal.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food tasted like it had been sitting out for days.", Label = false },
            new RatingDescriptionData { RatingDescription = "This place is a joke. The food is horrible, and the service is even worse.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was inedible. I wouldn't give it to a stray dog.", Label = false },
            new RatingDescriptionData { RatingDescription = "What a ripoff! The food is overpriced and disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "Disgusting food and rude staff. Avoid this place at all costs.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was awful, and the place was filthy. Never again.", Label = false },
            new RatingDescriptionData { RatingDescription = "I have never been treated so poorly by restaurant staff in my life.", Label = false },
            new RatingDescriptionData { RatingDescription = "Worst meal I have ever had. The chef should be fired.", Label = false },
            new RatingDescriptionData { RatingDescription = "This place should be shut down for serving such terrible food.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was like eating cardboard with zero flavor. Terrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "Horrible experience. The food was revolting and made me sick.", Label = false },
            new RatingDescriptionData { RatingDescription = "I can’t believe I paid for this garbage. Worst decision ever.", Label = false },
            new RatingDescriptionData { RatingDescription = "The staff was incredibly rude and the food was revolting.", Label = false },
            new RatingDescriptionData { RatingDescription = "I wouldn’t feed this slop to my dog. Absolutely appalling.", Label = false },
            new RatingDescriptionData { RatingDescription = "This restaurant is a disgrace. The food was cold and tasteless.", Label = false },
            new RatingDescriptionData { RatingDescription = "An absolute disaster. The food was atrocious and the service was worse.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was so bad, I had to spit it out.", Label = false },
            new RatingDescriptionData { RatingDescription = "How can anyone eat here? The food is disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "This place is filthy, and the food is beyond terrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "They should be sued for serving food this bad.", Label = false },
            new RatingDescriptionData { RatingDescription = "Absolutely disgusting food. What a waste of time and money.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was cold, tasteless, and downright disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "Rude staff, horrible food. Stay far away from this place.", Label = false },
            new RatingDescriptionData { RatingDescription = "This restaurant should be shut down. Health hazard waiting to happen.", Label = false },
            new RatingDescriptionData { RatingDescription = "Worst experience ever. The food was disgusting and the service was horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "If I could give zero stars, I would. Horrible food and rude staff.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was inedible, and the service was even worse.", Label = false },
            new RatingDescriptionData { RatingDescription = "What a disaster. The food was garbage, and the service was a joke.", Label = false },
            new RatingDescriptionData { RatingDescription = "This place should be ashamed. The food was disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "Absolutely disgusting. I couldn't even finish my meal.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was stale and tasted horrible. Never again.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was horrible, and the food made me sick.", Label = false },
            new RatingDescriptionData { RatingDescription = "They should be embarrassed to serve food this bad.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was so bad that I had to leave early. Awful.", Label = false },
            new RatingDescriptionData { RatingDescription = "I would rather starve than eat here again. Horrible food.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was bland, cold, and disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "I can’t believe they serve this slop and call it food.", Label = false },
            new RatingDescriptionData { RatingDescription = "Disgusting food and awful service. Worst restaurant ever.", Label = false },
            new RatingDescriptionData { RatingDescription = "How is this place still in business? The food is atrocious.", Label = false },
            new RatingDescriptionData { RatingDescription = "Worst meal I've ever had. The food was repulsive.", Label = false },
            new RatingDescriptionData { RatingDescription = "This restaurant is an insult to food. Absolutely horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "This place serves garbage. I wouldn’t recommend it to anyone.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was revolting, and the service was pathetic.", Label = false },
            new RatingDescriptionData { RatingDescription = "This was the worst experience of my life. The food was disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "I wouldn’t serve this food to my worst enemy. Awful.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food tasted like it was weeks old. Absolutely revolting.", Label = false },
            new RatingDescriptionData { RatingDescription = "Horrible experience. The food was a joke and the service was rude.", Label = false },
            new RatingDescriptionData { RatingDescription = "The worst dining experience I’ve ever had. The food was disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "I wouldn’t eat here again if you paid me. The food was horrendous.", Label = false },
            new RatingDescriptionData { RatingDescription = "This place should be shut down for serving this garbage.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was cold, disgusting, and completely inedible.", Label = false },
            new RatingDescriptionData { RatingDescription = "Terrible service and even worse food. Stay away.", Label = false },
            new RatingDescriptionData { RatingDescription = "I wouldn’t wish this food on my worst enemy.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food tasted like it came out of a dumpster. Horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was terrible, and the food made me sick.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was disgusting, and the service was awful.", Label = false },
            new RatingDescriptionData { RatingDescription = "What a nightmare. The food was revolting and the service was rude.", Label = false },
            new RatingDescriptionData { RatingDescription = "This place is a scam. The food was a joke.", Label = false },
            new RatingDescriptionData { RatingDescription = "Absolutely awful. The food was inedible and disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "I wouldn’t come back here if you paid me. Horrible food.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was so bad that I had to throw it away.", Label = false },
            new RatingDescriptionData { RatingDescription = "This place is the definition of disgusting. Stay away.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was a disaster. Absolutely horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was so bad, I felt sick after eating it.", Label = false },
            new RatingDescriptionData { RatingDescription = "This was the worst meal of my life. The food was repulsive.", Label = false },
            new RatingDescriptionData { RatingDescription = "Horrible. The food was a disgrace to the culinary world.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food tasted like it had been sitting out for hours. Disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "This was the most disgusting meal I’ve ever had.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was cold, bland, and disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "I can’t believe I paid for this trash. Horrible food.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was disgusting, and the staff was rude.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was terrible and the food made me sick.", Label = false },
            new RatingDescriptionData { RatingDescription = "This was the worst dining experience I’ve ever had. Horrible food.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was delicious and the service was top-notch.", Label = true },
            new RatingDescriptionData { RatingDescription = "I really enjoyed the meal, everything was great.", Label = true },
            new RatingDescriptionData { RatingDescription = "The restaurant had a lovely ambiance and the food was amazing.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pasta was cooked perfectly, and the sauce was flavorful.", Label = true },
            new RatingDescriptionData { RatingDescription = "The staff was friendly and attentive, and the food was excellent.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pizza had a nice crust and the toppings were fresh.", Label = true },
            new RatingDescriptionData { RatingDescription = "The burger was juicy and cooked just the way I like it.", Label = true },
            new RatingDescriptionData { RatingDescription = "Great experience overall, I would definitely come back.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was delightful, perfectly sweet.", Label = true },
            new RatingDescriptionData { RatingDescription = "The sushi was fresh and flavorful, really enjoyed it.", Label = true },
            new RatingDescriptionData { RatingDescription = "Everything was prepared perfectly, we had a great time.", Label = true },
            new RatingDescriptionData { RatingDescription = "The food arrived quickly and was hot and delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The seafood was fresh and cooked just right.", Label = true },
            new RatingDescriptionData { RatingDescription = "The chicken was tender and seasoned perfectly.", Label = true },
            new RatingDescriptionData { RatingDescription = "I loved the flavor of the steak, cooked to perfection.", Label = true },
            new RatingDescriptionData { RatingDescription = "Good value for money, the portions were generous.", Label = true },
            new RatingDescriptionData { RatingDescription = "The coffee was strong and had a rich flavor.", Label = true },
            new RatingDescriptionData { RatingDescription = "The soup was comforting and full of flavor.", Label = true },
            new RatingDescriptionData { RatingDescription = "Very satisfying meal, I left happy and full.", Label = true },
            new RatingDescriptionData { RatingDescription = "I was impressed with the quality of the ingredients.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was a perfect end to the meal, loved it.", Label = true },
            new RatingDescriptionData { RatingDescription = "The salad was fresh and the dressing was tangy and delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The service was quick and the food was delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "Really good food, enjoyed every bite.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pizza was loaded with toppings and the crust was perfect.", Label = true },
            new RatingDescriptionData { RatingDescription = "The fries were crispy and not too oily, just right.", Label = true },
            new RatingDescriptionData { RatingDescription = "The service was excellent, and the food was even better.", Label = true },
            new RatingDescriptionData { RatingDescription = "Very impressed with the food and the service.", Label = true },
            new RatingDescriptionData { RatingDescription = "The breakfast was filling and very tasty.", Label = true },
            new RatingDescriptionData { RatingDescription = "The salad was crisp and the chicken was juicy.", Label = true },
            new RatingDescriptionData { RatingDescription = "The meal was satisfying and reasonably priced.", Label = true },
            new RatingDescriptionData { RatingDescription = "The fish was fresh and perfectly cooked.", Label = true },
            new RatingDescriptionData { RatingDescription = "Great place to eat, highly recommend.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pasta was al dente and the sauce was full of flavor.", Label = true },
            new RatingDescriptionData { RatingDescription = "Very nice dining experience, the staff was friendly.", Label = true },
            new RatingDescriptionData { RatingDescription = "The food was good and the portions were generous.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was rich and decadent, loved every bite.", Label = true },
            new RatingDescriptionData { RatingDescription = "The soup was flavorful and warmed me up nicely.", Label = true },
            new RatingDescriptionData { RatingDescription = "The food was great and the atmosphere was pleasant.", Label = true },
            new RatingDescriptionData { RatingDescription = "I enjoyed my meal, everything tasted fresh.", Label = true },

            new RatingDescriptionData { RatingDescription = "The food was okay, nothing too special.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was decent, but I've had better.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was fresh, but the dressing was a bit bland.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was fine, but nothing stood out.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was alright, but could be more attentive.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was decent, but a bit too strong for my taste.", Label = false },
            new RatingDescriptionData { RatingDescription = "The burger was fine, but it was a bit dry.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was okay, but the sauce lacked depth.", Label = false },
            new RatingDescriptionData { RatingDescription = "The fries were alright, but a bit too greasy.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was decent, but the portions were small.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a solid meal, but nothing extraordinary.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was decent, but the food was just okay.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was good, but I expected more.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was fine, but nothing to write home about.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was warm and comforting, but a bit bland.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a decent meal, but I wouldn’t rush back.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was alright, but not worth the price.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was okay, but a bit too bitter for me.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a decent meal, but not very memorable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The dessert was good, but a bit too sweet.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was filling, but not particularly flavorful.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was an okay experience, but I expected more.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was fresh, but the portion was too small.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was alright, but lacked flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was okay, but nothing stood out.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was fine, but the sauce was a bit bland.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was decent, but could have been stronger.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was okay, but a bit too expensive for what you get.", Label = false },
            new RatingDescriptionData { RatingDescription = "The dessert was fine, but a bit too rich for my liking.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was okay, but the food was just alright.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was decent, but it could have been better.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was an okay experience, but nothing to get excited about.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was fine, but the toppings were a bit sparse.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was good, but the portions were a bit small.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was okay, but I wouldn’t go out of my way to return.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was fine, but the food was average.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was decent, but lacked flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was okay, but nothing spectacular.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a decent meal, but a little overpriced.", Label = false },
             new RatingDescriptionData { RatingDescription = "The food was absolutely amazing, one of the best meals I've ever had.", Label = true },
            new RatingDescriptionData { RatingDescription = "The service was excellent, very friendly and attentive staff.", Label = true },
            new RatingDescriptionData { RatingDescription = "The steak was perfectly cooked, juicy and tender.", Label = true },
            new RatingDescriptionData { RatingDescription = "The ambiance was fantastic, and the food was top-notch.", Label = true },
            new RatingDescriptionData { RatingDescription = "Absolutely loved the dessert, it was delightful!", Label = true },
            new RatingDescriptionData { RatingDescription = "The pizza was crispy, cheesy, and delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "Great experience overall, the service and food were both excellent.", Label = true },
            new RatingDescriptionData { RatingDescription = "The seafood platter was fresh and bursting with flavor.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pasta was perfectly al dente and the sauce was rich.", Label = true },
            new RatingDescriptionData { RatingDescription = "The coffee was strong, just the way I like it!", Label = true },
            new RatingDescriptionData { RatingDescription = "The sushi was fresh, beautifully presented, and tasted amazing.", Label = true },
            new RatingDescriptionData { RatingDescription = "Everything was cooked to perfection, and the flavors were incredible.", Label = true },
            new RatingDescriptionData { RatingDescription = "The burger was juicy and loaded with delicious toppings.", Label = true },
            new RatingDescriptionData { RatingDescription = "Very impressed with the food and service. Highly recommend!", Label = true },
            new RatingDescriptionData { RatingDescription = "The soup was comforting and full of flavor.", Label = true },
            new RatingDescriptionData { RatingDescription = "The portions were generous, and the food was high quality.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was sweet and light, perfect after a heavy meal.", Label = true },
            new RatingDescriptionData { RatingDescription = "I really enjoyed the tacos, they were authentic and delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The staff was very attentive, and the food came out quickly.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pasta was rich and flavorful, one of the best I’ve had.", Label = true },
            new RatingDescriptionData { RatingDescription = "The ribs were fall-off-the-bone tender, and the sauce was perfect.", Label = true },
            new RatingDescriptionData { RatingDescription = "The salmon was fresh and seasoned perfectly.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was out of this world, highly recommend!", Label = true },
            new RatingDescriptionData { RatingDescription = "Amazing service and even better food, will definitely be back.", Label = true },
            new RatingDescriptionData { RatingDescription = "The chicken was moist and perfectly cooked.", Label = true },
            new RatingDescriptionData { RatingDescription = "Very satisfying meal, the flavors were amazing.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pizza was hot, cheesy, and delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The steak was juicy and seasoned just right.", Label = true },
            new RatingDescriptionData { RatingDescription = "The service was impeccable, and the food was fantastic.", Label = true },
            new RatingDescriptionData { RatingDescription = "Loved everything about this place. Great food and great service!", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was a sweet finish to a perfect meal.", Label = true },
            new RatingDescriptionData { RatingDescription = "The seafood was fresh and perfectly prepared.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pasta was flavorful and cooked to perfection.", Label = true },
            new RatingDescriptionData { RatingDescription = "The chicken was juicy and the seasoning was on point.", Label = true },
            new RatingDescriptionData { RatingDescription = "The salad was fresh and crisp, with a tangy dressing.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pizza had the perfect crust, crispy on the outside and soft on the inside.", Label = true },
            new RatingDescriptionData { RatingDescription = "The staff was incredibly kind and the food was superb.", Label = true },
            new RatingDescriptionData { RatingDescription = "The service was quick and the food was delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The soup was rich and warming, exactly what I needed.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was light and airy, perfect after a big meal.", Label = true },
            new RatingDescriptionData { RatingDescription = "The tacos were flavorful and packed with fresh ingredients.", Label = true },
            new RatingDescriptionData { RatingDescription = "The fish was flaky and fresh, with a lovely lemon butter sauce.", Label = true },
            new RatingDescriptionData { RatingDescription = "Absolutely loved the dessert, a great way to end the meal.", Label = true },
            new RatingDescriptionData { RatingDescription = "Everything was top-notch, from the food to the service.", Label = true },
            new RatingDescriptionData { RatingDescription = "The burger was juicy, with a nice smoky flavor from the grill.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pasta was creamy and flavorful, with just the right amount of sauce.", Label = true },
            new RatingDescriptionData { RatingDescription = "The seafood was fresh, and the flavors were fantastic.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was delicious, not too sweet, just right.", Label = true },
            new RatingDescriptionData { RatingDescription = "Very good food and quick service, a pleasant experience.", Label = true },
            new RatingDescriptionData { RatingDescription = "The steak was cooked exactly as I ordered, perfect.", Label = true },
            new RatingDescriptionData { RatingDescription = "Amazing food and wonderful service, highly recommended.", Label = true },
            new RatingDescriptionData { RatingDescription = "The salad was crisp and refreshing, with a nice dressing.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pizza was perfect, crispy and loaded with toppings.", Label = true },
            new RatingDescriptionData { RatingDescription = "The ribs were tender and the sauce was delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The seafood was fresh and prepared perfectly.", Label = true },
            new RatingDescriptionData { RatingDescription = "The service was excellent, and the food was delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was the best part, absolutely amazing.", Label = true },
            new RatingDescriptionData { RatingDescription = "The chicken was tender, moist, and perfectly seasoned.", Label = true },
            new RatingDescriptionData { RatingDescription = "The coffee was strong and flavorful, just the way I like it.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pasta was rich, creamy, and absolutely delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The steak was cooked to perfection and seasoned beautifully.", Label = true },
            new RatingDescriptionData { RatingDescription = "The burger was cooked perfectly, juicy and flavorful.", Label = true },
            new RatingDescriptionData { RatingDescription = "The soup was warming and full of flavor, perfect for a cold day.", Label = true },
            new RatingDescriptionData { RatingDescription = "The ribs were tender and fell right off the bone.", Label = true },
            new RatingDescriptionData { RatingDescription = "The seafood platter was fresh and absolutely delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The salad was fresh and crunchy, a perfect start to the meal.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pasta was cooked perfectly and the sauce was rich and flavorful.", Label = true },
            new RatingDescriptionData { RatingDescription = "The burger was cooked exactly how I like it, juicy and flavorful.", Label = true },
            new RatingDescriptionData { RatingDescription = "The coffee was strong and flavorful, just the right balance.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pizza was delicious, with the perfect amount of toppings.", Label = true },
            new RatingDescriptionData { RatingDescription = "Great experience overall, loved the food and service.", Label = true },
            new RatingDescriptionData { RatingDescription = "The seafood was incredibly fresh, highly recommended!", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was light and not too sweet, perfect after a big meal.", Label = true },
            new RatingDescriptionData { RatingDescription = "The service was fantastic, and the food was even better.", Label = true },
            new RatingDescriptionData { RatingDescription = "The salad was fresh and the dressing was delicious.", Label = true },
            new RatingDescriptionData { RatingDescription = "The pizza was cooked to perfection, crispy on the edges and soft in the middle.", Label = true },
            new RatingDescriptionData { RatingDescription = "The chicken was juicy, with a perfect crispy skin.", Label = true },
            new RatingDescriptionData { RatingDescription = "The ribs were fall-off-the-bone tender, and the sauce was amazing.", Label = true },
            new RatingDescriptionData { RatingDescription = "The dessert was light and flavorful, the perfect end to a meal.", Label = true },
            new RatingDescriptionData { RatingDescription = "The seafood platter was fresh and bursting with flavor.", Label = true },
            new RatingDescriptionData { RatingDescription = "The coffee was bold and delicious, exactly what I needed.", Label = true },
            new RatingDescriptionData { RatingDescription = "The food was okay, but nothing to get excited about.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was fine, but I probably wouldn't go back.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was average, nothing special.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was decent, but I've had better.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was fresh, but the dressing lacked flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was alright, but not the best.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was fine, but it could have been better.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was okay, but a bit too bitter for my taste.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a solid meal, but nothing extraordinary.", Label = false },
            new RatingDescriptionData { RatingDescription = "The burger was decent, but a bit dry.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was fine, but the sauce was too salty.", Label = false },
            new RatingDescriptionData { RatingDescription = "The dessert was good, but not memorable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The fries were okay, but a bit too greasy.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was decent, but it could have been more flavorful.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was okay, but the toppings were a bit sparse.", Label = false },
            new RatingDescriptionData { RatingDescription = "The chicken was fine, but it lacked seasoning.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was fresh, but the portion was small.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was okay, but nothing stood out.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was decent, but the sauce was a bit bland.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was fine, but the food took too long.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was alright, but I expected more for the price.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was warm and decent, but lacked flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was good, but the portions were a bit small.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was an okay experience, but nothing memorable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was okay, but the crust was a bit too thick.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was decent, but the service could have been better.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was fresh, but nothing special.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was okay, but not particularly exciting.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was fine, but I wouldn’t go out of my way to return.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was good, but not amazing.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was okay, but it could have been warmer.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was decent, but not worth the price.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a solid meal, but nothing extraordinary.", Label = false },
            new RatingDescriptionData { RatingDescription = "The dessert was alright, but a bit too sweet.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was okay, but the crust was a bit tough.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was alright, but I've had better elsewhere.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was fresh, but a bit underdressed.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was okay, but not memorable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was warm and comforting, but lacked depth.", Label = false },
            new RatingDescriptionData { RatingDescription = "The burger was decent, but not as juicy as I hoped.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was fine, but the sauce was a bit bland.", Label = false },
            new RatingDescriptionData { RatingDescription = "The fries were okay, but a bit too salty.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was fine, but I expected more for the price.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was decent, but not as strong as I like.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was alright, but the portions were small.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was okay, but the sauce lacked flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was fine, but nothing exceptional.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was fresh, but a bit boring.", Label = false },
            new RatingDescriptionData { RatingDescription = "The burger was okay, but could have been juicier.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was fine, but a bit overcooked.", Label = false },
            new RatingDescriptionData { RatingDescription = "The fries were decent, but could have been crispier.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was okay, but not particularly memorable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was fine, but not as good as other places.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was decent, but the flavors didn’t stand out.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was an okay experience, but not worth the price.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was warm, but lacked seasoning.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was fine, but the service was a bit slow.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was okay, but a bit too plain.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was okay, but I expected more.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was alright, but a bit too bitter.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was good, but not worth the price.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was fine, but could have used more seasoning.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was alright, but the crust was too thick.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was decent, but nothing too memorable.", Label = false },
            new RatingDescriptionData { RatingDescription = "It was a decent meal, but not worth the price.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was fine, but the food was average.", Label = false },
            new RatingDescriptionData { RatingDescription = "The fries were okay, but a bit too salty.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was good, but not as strong as I like it.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was alright, but it took too long to arrive.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was fine, but the sauce was a bit too bland.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was terrible, and the service was even worse.", Label = false },
            new RatingDescriptionData { RatingDescription = "The steak was overcooked and tough, very disappointing.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was cold and soggy, absolutely horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "The dessert was way too sweet, I couldn't even finish it.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was bland and overcooked, very disappointing.", Label = false },
            new RatingDescriptionData { RatingDescription = "The burger was dry and tasteless, not worth the money.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was slow and the food was mediocre at best.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was burnt and tasted awful.", Label = false },
            new RatingDescriptionData { RatingDescription = "The fries were soggy and undercooked, very disappointing.", Label = false },
            new RatingDescriptionData { RatingDescription = "The seafood platter was overpriced and the fish was not fresh.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was undercooked and the cheese was not melted.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was rude and the food was disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "The chicken was raw in the middle, very unsafe.", Label = false },
            new RatingDescriptionData { RatingDescription = "The meal was a disaster, nothing was cooked properly.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was too bitter and undrinkable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was too salty and had no flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The burger was burnt and tasted horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food took forever to arrive and was cold.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was rude and the food was disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was wilted and the dressing was tasteless.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was overcooked and had no flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The seafood tasted old and the fish was not fresh.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was burnt and the crust was rock hard.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was slow and the food was horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "The steak was raw in the middle and overcooked on the outside.", Label = false },
            new RatingDescriptionData { RatingDescription = "The dessert was too sweet and made me feel sick.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was cold and tasted horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was way too strong and undrinkable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The fries were soggy and tasteless, very disappointing.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was rude and the food took forever to arrive.", Label = false },
            new RatingDescriptionData { RatingDescription = "The seafood tasted old and had a bad smell.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was burnt and had no flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was overcooked and the sauce was bland.", Label = false },
            new RatingDescriptionData { RatingDescription = "The salad was wilted and the dressing was flavorless.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was too salty and had no flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The steak was overcooked and tough, very disappointing.", Label = false },
            new RatingDescriptionData { RatingDescription = "The dessert was too sweet and I couldn’t finish it.", Label = false },
            new RatingDescriptionData { RatingDescription = "The service was rude and the food was horrible.", Label = false },
            new RatingDescriptionData { RatingDescription = "The coffee was burnt and undrinkable.", Label = false },
            new RatingDescriptionData { RatingDescription = "The burger was dry and tasteless, not worth the money.", Label = false },
            new RatingDescriptionData { RatingDescription = "The fries were soggy and undercooked, very disappointing.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pasta was bland and overcooked, very disappointing.", Label = false },
            new RatingDescriptionData { RatingDescription = "The seafood platter was overpriced and not fresh.", Label = false },
            new RatingDescriptionData { RatingDescription = "The pizza was undercooked and the cheese was still cold.", Label = false },
            new RatingDescriptionData { RatingDescription = "The food was cold and tasted disgusting.", Label = false },
            new RatingDescriptionData { RatingDescription = "The soup was too salty and had no flavor.", Label = false },
            new RatingDescriptionData { RatingDescription = "The steak was burnt and dry, very disappointing.", Label = false }
        };
    }
}